# Generated by Django 3.1.2 on 2020-12-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='status',
            field=models.CharField(default=1, max_length=9, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mal',
            name='count',
            field=models.CharField(max_length=10000, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='mal',
            name='data_1',
            field=models.CharField(max_length=26, verbose_name='First Recorded Date'),
        ),
        migrations.AlterField(
            model_name='mal',
            name='data_2',
            field=models.CharField(max_length=26, verbose_name='Last Recorded Date'),
        ),
        migrations.AlterField(
            model_name='mal',
            name='ip',
            field=models.CharField(max_length=19, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='mal',
            name='rede',
            field=models.CharField(max_length=40, verbose_name='Network'),
        ),
        migrations.AlterField(
            model_name='other',
            name='count',
            field=models.CharField(max_length=10000, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='other',
            name='data_1',
            field=models.CharField(max_length=26, verbose_name='First Recorded Date'),
        ),
        migrations.AlterField(
            model_name='other',
            name='data_2',
            field=models.CharField(max_length=26, verbose_name='Last Recorded Date'),
        ),
        migrations.AlterField(
            model_name='other',
            name='ip',
            field=models.CharField(max_length=19, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='other',
            name='rede',
            field=models.CharField(max_length=40, verbose_name='Network'),
        ),
        migrations.AlterField(
            model_name='records',
            name='data_1',
            field=models.CharField(max_length=26, verbose_name='First Recorded Date'),
        ),
        migrations.AlterField(
            model_name='records',
            name='data_2',
            field=models.CharField(max_length=26, verbose_name='Last Recorded Date'),
        ),
        migrations.AlterField(
            model_name='records',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='records',
            name='email_sent',
            field=models.CharField(max_length=9, verbose_name='Email Sent Type'),
        ),
        migrations.AlterField(
            model_name='records',
            name='ip',
            field=models.CharField(max_length=19, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='records',
            name='rede',
            field=models.CharField(max_length=40, verbose_name='Network'),
        ),
        migrations.AlterField(
            model_name='records',
            name='tipo',
            field=models.CharField(max_length=13, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='vul',
            name='count',
            field=models.CharField(max_length=10000, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='vul',
            name='data_1',
            field=models.CharField(max_length=26, verbose_name='First Recorded Date'),
        ),
        migrations.AlterField(
            model_name='vul',
            name='data_2',
            field=models.CharField(max_length=26, verbose_name='Last Recorded Date'),
        ),
        migrations.AlterField(
            model_name='vul',
            name='ip',
            field=models.CharField(max_length=19, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='vul',
            name='port',
            field=models.CharField(max_length=10000, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='vul',
            name='rede',
            field=models.CharField(max_length=40, verbose_name='Network'),
        ),
    ]
