# Generated by Django 3.1.2 on 2020-12-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20201219_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='status',
            field=models.CharField(max_length=11, verbose_name='Status'),
        ),
    ]
