# Generated by Django 3.1.2 on 2020-12-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20201219_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='data_1',
        ),
        migrations.RemoveField(
            model_name='records',
            name='data_2',
        ),
        migrations.RemoveField(
            model_name='records',
            name='rede',
        ),
        migrations.AddField(
            model_name='records',
            name='data',
            field=models.CharField(default=1, max_length=26, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
